services:
  web:
    build: .
    image: crashtracker
    ports:
      - "7027:7027"  
    depends_on:
      - db
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7027
      - ConnectionStrings__Postgres=Host=db;Database=CrashTracker;Username=postgres;Password=admin
      - Redis__ConnectionString=redis:6379
    restart: always

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: CrashTracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  redis:
    image: redis:7
    command: ["redis-server", "--save", "20 1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
